src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>List__c</fullName>
        <label>List</label>
        <referenceTo>List__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/List__c.object
<CustomObject>
    <label>List</label>
    <nameField>
        <label>List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Related_Items__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Related_Item__c</fullName>
        <description>Item usually bought with primary item</description>
        <label>Related Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Related Items</label>
</CustomObject>

src/classes/ItemTriggerHelper.cls
public class ItemTriggerHelper{
    public static void insertRelatedItems(List<Item__c> items){
        List<Item__c> ListOfRelatedItems = new List<Item__c>();
        //get custom setting values: Related_Items__c
        List<Related_Items__c> relatedItems = Related_Items__c.getAll().values();
        for(Item__c item: items){
            for(Related_Items__c relatedItem: relatedItems){
                if(item.Name == relatedItem.Name){
                 	Item__c newitem = new Item__c();
                    newitem.Name = relatedItem.Related_Item__c;
                    newitem.Quantity__c = relatedItem.Quantity__c;
                    newitem.List__c = item.List__c;
                    ListOfRelatedItems.add(newItem);
                }
            }
        }
        
        if(ListOfRelatedItems.size() > 0 && ListOfRelatedItems!=null){
         	insert ListOfRelatedItems;   
        }
    }
}